version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps/
    overwrite: yes
permissions:
  - object: /opt/tomcat/webapps/app.war
    owner: tomcat
    group: tomcat
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      runas: root
  AfterInstall:
    - location: scripts/server.sh
      runas: root